name: Test
on: pull_request
jobs: 
  test-js: 
    runs-on: ubuntu-latest
    name:  "${{ matrix.os }} node:${{ matrix.node }}"
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        node: ["18", "20"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: yarn
          cache-dependency-path: yarn.lock
      - name: Install latest Rust nightly
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly-2023-07-27
          components: rustfmt, clippy
      - run: yarn --version
      - name: Install Node Dependencies
        run: yarn install
      - name: Build Binary
        run: yarn build:debug
      - name: Run Linting
        run: yarn lint:ts
      - name: Run Tests
        run: yarn test
      - name: Build JS
        run: yarn build:ts
      - name: Bum version
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Bun Install Dependencies
        run: bun install
      - name: Bun Build Binary
        run: bun run build:debug
      - name: Bun Run Tests
        run: bun run test
      - name: Bun Build JS
        run: bun run build:ts
