name: nodejs-polars
env:
  DEBUG: napi:*
  APP_NAME: nodejs-polars
  MACOSX_DEPLOYMENT_TARGET: "26.0"
"on":
  push:
    branches:
      - unpublish-0.25.0
permissions:
  id-token: write  # Required for OIDC
  contents: read

jobs:
  publish:
    name: Unpublish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 26
          registry-url: "https://registry.npmjs.org"

      - name: Unpublish to npm
        # run: npm unpublish nodejs-polars@0.25.0 --force
        run: npm deprecate nodejs-polars@0.25.0 "This version has been unpublished due to critical issues. Please use a later version." 
